// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5klWp5wknN73Ikd3QR9jSdiPNC-D-RzE',
    appId: '1:1087464889225:web:0e01dfd0963e21d4f65f58',
    messagingSenderId: '1087464889225',
    projectId: 'expensetracker694',
    authDomain: 'expensetracker694.firebaseapp.com',
    storageBucket: 'expensetracker694.firebasestorage.app',
    measurementId: 'G-Q7LVQJQHG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvG_imojoELkyvqgzIe_i-0dJNAxaEpAs',
    appId: '1:1087464889225:android:42dd3d62b011ea20f65f58',
    messagingSenderId: '1087464889225',
    projectId: 'expensetracker694',
    storageBucket: 'expensetracker694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzhb0mZrMZQYpEhXVZD1S2pmkZQLINoL4',
    appId: '1:1087464889225:ios:02c2b86bb49633eaf65f58',
    messagingSenderId: '1087464889225',
    projectId: 'expensetracker694',
    storageBucket: 'expensetracker694.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzhb0mZrMZQYpEhXVZD1S2pmkZQLINoL4',
    appId: '1:1087464889225:ios:02c2b86bb49633eaf65f58',
    messagingSenderId: '1087464889225',
    projectId: 'expensetracker694',
    storageBucket: 'expensetracker694.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5klWp5wknN73Ikd3QR9jSdiPNC-D-RzE',
    appId: '1:1087464889225:web:f599e3de841af479f65f58',
    messagingSenderId: '1087464889225',
    projectId: 'expensetracker694',
    authDomain: 'expensetracker694.firebaseapp.com',
    storageBucket: 'expensetracker694.firebasestorage.app',
    measurementId: 'G-X212YW8Z2S',
  );
}
